create table if not exists public.comment_images (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null,
  image_url text not null,
  created_at timestamptz not null default now()
);

alter table public.comment_images enable row level security;

grant select on table public.comment_images to anon;
grant select, insert, delete on table public.comment_images to authenticated;
grant usage, select on sequence public.comment_images_id_seq to authenticated;

drop policy if exists "Comment images are publicly readable"
on public.comment_images;

create policy "Comment images are publicly readable"
on public.comment_images for select
using (true);

drop policy if exists "Users create their own comment images"
on public.comment_images;

create policy "Users create their own comment images"
on public.comment_images for insert
with check (auth.uid() = user_id);

drop policy if exists "Users delete their own comment images"
on public.comment_images;

create policy "Users delete their own comment images"
on public.comment_images for delete
using (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('comment-images', 'comment-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Public comment image access"
on storage.objects;

create policy "Public comment image access"
on storage.objects for select
using (bucket_id = 'comment-images');

drop policy if exists "Users upload comment images"
on storage.objects;

create policy "Users upload comment images"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'comment-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users delete comment images"
on storage.objects;

create policy "Users delete comment images"
on storage.objects for delete to authenticated
using (
  bucket_id = 'comment-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

notify pgrst, 'reload schema';

create or replace function public.enforce_max_post_images()
returns trigger
language plpgsql
as $$
begin
  if (
    select count(*)
    from public.post_images
    where post_id = new.post_id
  ) >= 5 then
    raise exception 'A post can only have up to 5 images.';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_max_post_images_trigger
on public.post_images;

create trigger enforce_max_post_images_trigger
before insert on public.post_images
for each row execute function public.enforce_max_post_images();

create or replace function public.enforce_max_comment_images()
returns trigger
language plpgsql
as $$
begin
  if (
    select count(*)
    from public.comment_images
    where comment_id = new.comment_id
  ) >= 5 then
    raise exception 'A comment can only have up to 5 images.';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_max_comment_images_trigger
on public.comment_images;

create trigger enforce_max_comment_images_trigger
before insert on public.comment_images
for each row execute function public.enforce_max_comment_images();
