create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  title text not null,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_images (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null,
  image_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comment_images (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null,
  image_url text not null,
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;
alter table public.post_images enable row level security;
alter table public.comments enable row level security;
alter table public.comment_images enable row level security;

grant select on table public.posts to anon, authenticated;
grant select on table public.post_images to anon, authenticated;
grant select on table public.comments to anon, authenticated;
grant select on table public.comment_images to anon, authenticated;

grant insert, update, delete on table public.posts to authenticated;
grant insert, delete on table public.post_images to authenticated;
grant insert, update, delete on table public.comments to authenticated;
grant insert, delete on table public.comment_images to authenticated;

grant usage, select on all sequences in schema public to authenticated;

create policy "Posts are publicly readable"
on public.posts for select
using (true);

create policy "Users create their own posts"
on public.posts for insert
with check (auth.uid() = user_id);

create policy "Users update their own posts"
on public.posts for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users delete their own posts"
on public.posts for delete
using (auth.uid() = user_id);

create policy "Post images are publicly readable"
on public.post_images for select
using (true);

create policy "Users create their own post images"
on public.post_images for insert
with check (auth.uid() = user_id);

create policy "Users delete their own post images"
on public.post_images for delete
using (auth.uid() = user_id);

create policy "Comments are publicly readable"
on public.comments for select
using (true);

create policy "Users create their own comments"
on public.comments for insert
with check (auth.uid() = user_id);

create policy "Users update their own comments"
on public.comments for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users delete their own comments"
on public.comments for delete
using (auth.uid() = user_id);

create policy "Comment images are publicly readable"
on public.comment_images for select
using (true);

create policy "Users create their own comment images"
on public.comment_images for insert
with check (auth.uid() = user_id);

create policy "Users delete their own comment images"
on public.comment_images for delete
using (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('post-images', 'post-images', true)
on conflict (id) do update set public = true;

insert into storage.buckets (id, name, public)
values ('comment-images', 'comment-images', true)
on conflict (id) do update set public = true;

create policy "Public post image access"
on storage.objects for select
using (bucket_id = 'post-images');

create policy "Users upload post images"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'post-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users delete post images"
on storage.objects for delete to authenticated
using (
  bucket_id = 'post-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Public comment image access"
on storage.objects for select
using (bucket_id = 'comment-images');

create policy "Users upload comment images"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'comment-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Users delete comment images"
on storage.objects for delete to authenticated
using (
  bucket_id = 'comment-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create or replace function public.enforce_max_post_images()
returns trigger
language plpgsql
as $$
begin
  if (
    select count(*)
    from public.post_images
    where post_id = new.post_id
  ) >= 5 then
    raise exception 'A post can only have up to 5 images.';
  end if;

  return new;
end;
$$;

create trigger enforce_max_post_images_trigger
before insert on public.post_images
for each row execute function public.enforce_max_post_images();

create or replace function public.enforce_max_comment_images()
returns trigger
language plpgsql
as $$
begin
  if (
    select count(*)
    from public.comment_images
    where comment_id = new.comment_id
  ) >= 5 then
    raise exception 'A comment can only have up to 5 images.';
  end if;

  return new;
end;
$$;

create trigger enforce_max_comment_images_trigger
before insert on public.comment_images
for each row execute function public.enforce_max_comment_images();
